name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Creating env
        run: |
          touch .env
          echo VITE_API_BASE_URL = ${{ secrets.VITE_API_BASE_URL }} >> .env
          echo VITE_BACKEND_BASE_URL = ${{ secrets.VITE_BACKEND_BASE_URL }} >> .env
          echo PUBLIC_FIREBASE_API_KEY = ${{ secrets.PUBLIC_FIREBASE_API_KEY }} >> .env
          echo PUBLIC_FIREBASE_AUTH_DOMAIN = ${{ secrets.PUBLIC_FIREBASE_AUTH_DOMAIN }} >> .env
          echo PUBLIC_FIREBASE_STORAGE_BUCKET = ${{ secrets.PUBLIC_FIREBASE_STORAGE_BUCKET }} >> .env
          echo PUBLIC_FIREBASE_PROJECT_ID = ${{ secrets.PUBLIC_FIREBASE_PROJECT_ID }} >> .env
          echo PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ${{ secrets.PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} >> .env
          echo PUBLIC_FIREBASE_APP_ID = ${{ secrets.PUBLIC_FIREBASE_APP_ID }} >> .env
          cat .env
      - name: Build and push Docker image
        run: |
          npm run image
          docker tag slcatering_fe:latest ${{ secrets.DOCKERHUB_USERNAME }}/slcatering_fe:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/slcatering_fe:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            cd slcatering-docker-fe/
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/slcatering_fe:latest
            docker compose down
            docker compose up -d
